# Generated by Django 4.1.4 on 2023-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('session', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(default='', max_length=8)),
                ('semester_no', models.IntegerField(default=None)),
                ('course_code', models.CharField(default='', max_length=8)),
                ('course_title', models.CharField(default='', max_length=60)),
                ('course_type', models.CharField(default='', max_length=10)),
                ('course_credits', models.FloatField(default=0)),
                ('course_teacher', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=None)),
                ('course_results', models.CharField(default='', max_length=1000)),
                ('current_semester_credits', models.FloatField(default=0)),
                ('current_semester_total_point', models.FloatField(default=0)),
                ('current_semester_GPA', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(default='', max_length=8)),
                ('semester_no', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SessionalCourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=None)),
                ('course_code', models.CharField(default='', max_length=8)),
                ('lab_marks', models.IntegerField(default=None)),
                ('assessment_marks', models.IntegerField(default=None)),
                ('total_marks', models.IntegerField(default=None)),
                ('GP', models.FloatField(default=0)),
                ('LG', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('session', models.CharField(default='', max_length=8)),
                ('name', models.CharField(default='', max_length=60)),
                ('father_name', models.CharField(default='', max_length=60)),
                ('mother_name', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
                ('isResidential', models.BooleanField(default=False)),
                ('isCR', models.BooleanField(default=False)),
                ('average_cgpa', models.FloatField(default=0)),
                ('remarks', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('designation', models.CharField(default='', max_length=60)),
                ('institute', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryCourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=None)),
                ('course_code', models.CharField(default='', max_length=8)),
                ('part_a_decode', models.CharField(default='', max_length=10)),
                ('part_a_marks', models.IntegerField(default=None)),
                ('part_b_decode', models.CharField(default='', max_length=10)),
                ('part_b_marks', models.IntegerField(default=None)),
                ('assessment_marks', models.IntegerField(default=None)),
                ('total_marks', models.IntegerField(default=None)),
                ('GP', models.FloatField(default=0)),
                ('LG', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
