# Generated by Django 4.1.4 on 2023-01-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
