# Generated by Django 4.1.4 on 2023-01-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='code',
        ),
    ]
