# Generated by Django 4.1.4 on 2023-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
