# Generated by Django 4.1.4 on 2023-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_student_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=0)),
                ('course_code', models.CharField(default='', max_length=8)),
                ('tt_mode', models.CharField(default='average', max_length=10)),
                ('tt_counting_on', models.IntegerField(default=20)),
                ('tt_results', models.CharField(default='', max_length=1000)),
                ('assignment_counting_on', models.IntegerField(default=10)),
                ('assignment_results', models.CharField(default='', max_length=1000)),
                ('attendance_counting_on', models.IntegerField(default=10)),
                ('attendance_results', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
